### ISSUE TITLE
visitor-badge.lithub.cc SSL certificate expired

### ISSUE THREAD

**Issue by LeDechaine** [lizheming/visitor-badge#1]
ZeroSSL certificate expired Thu, 28 Mar 2024 23:59:59 GMT.

Therefore any recent browser won't connect to the website, and the counter won't work (HTTPS Everywhere / HTTPS-only requires you to add an exception).

P.S.: "Let's Encrypt" ftw: It's free!

**Comment by lizheming** [comment]
thx for report! it has been fixed now, please try it again~
